# AGB SDK Documentation Push to GitHub Pipeline
name: "Push Documentation to GitHub"

params:
  github_repo:
    name: GitHub Repository
    type: string
    default: "agbcloud/agbcloud-docs"
    description: "Target GitHub repository (format: username/repo-name)"

  runs_on_resources:
    name: Resource Specification
    description: "Runtime container resource specification"
    default: "2-8Gi"
    options:
      - "2-8Gi"
      - "4-16Gi"
      - "8-32Gi"

jobs:
  push-docs-to-github:
    continue-on-error: false
    name: "Push Documentation to GitHub"
    runs-on:
      - "${{params.runs_on_resources}}"
    image: alios-8u
    timeout: 20m

    steps:
      - uses: checkout
        inputs:
          fetch-depth: 0
          ref: 'dev'
          username: 'wuying-ai-team'
          token: ${{secrets.wuying_ai_team_private_token}}

      # Check documentation changes
      - id: check-docs-changes
        name: "Check Documentation Changes"
        run: |
          echo "📋 Checking for documentation changes..."

          # Check if docs directory exists
          if [ ! -d "docs" ]; then
            echo "❌ docs directory not found"
            exit 1
          fi

          # Check if there are files in docs directory
          DOCS_FILES=$(find docs -type f -name "*.md" 2>/dev/null | wc -l)
          if [ "$DOCS_FILES" -eq 0 ]; then
            echo "⚠️ No markdown files found in docs directory"
            exit 1
          fi

          echo "✅ Found $DOCS_FILES documentation files"
          echo "DOCS_FILES_COUNT=$DOCS_FILES" >> $AONE_CI_ENV

          # Display documentation structure
          echo "📁 Documentation structure:"
          tree docs || find docs -type f | head -20

      # GitHub connectivity diagnosis step
      - id: github-connectivity-diagnosis
        name: "GitHub Connectivity Diagnosis"
        run: |
          echo "🔍 Running GitHub connectivity diagnosis..."
          echo "=================================="

          # Basic network connectivity test
          echo "1. Testing basic network connectivity:"
          if ping -c 3 8.8.8.8 > /dev/null 2>&1; then
            echo "   ✅ Internet connectivity: OK"
          else
            echo "   ⚠️ Internet connectivity: Limited (ping failed, trying HTTP)"
          fi



          # GitHub HTTPS connection
          echo "2. Testing GitHub HTTPS connectivity:"
          if curl -s --connect-timeout 10 https://github.com > /dev/null; then
            echo "   ✅ GitHub HTTPS connection: OK"
          else
            echo "   ❌ GitHub HTTPS connection: FAILED"
          fi

          # GitHub API connection
          echo "3. Testing GitHub API connectivity:"
          API_RESPONSE=$(curl -s -w "%{http_code}" https://api.github.com -o /dev/null)
          if [ "$API_RESPONSE" = "200" ]; then
            echo "   ✅ GitHub API connection: OK"
          else
            echo "   ❌ GitHub API connection: FAILED (HTTP $API_RESPONSE)"
          fi
          echo "=================================="
          echo "✅ Diagnosis completed"

      # Validate GitHub configuration
      - id: validate-github-config
        name: "Validate GitHub Configuration"
        run: |
          echo "🔧 Validating GitHub configuration..."

          # Check GitHub Token
          if [ -z "${{secrets.agbaccount_github_token}}" ]; then
            echo "❌ agbaccount_github_token not configured in GitLab secrets"
            echo "Please add agbaccount_github_token to GitLab CI/CD Variables"
            echo "Required permissions: repo, workflow"
            exit 1
          fi

          # Check GitHub username variable
          if [ -z "${{vars.agbaccount_github_username}}" ]; then
            echo "❌ agbaccount_github_username not configured in GitLab Variables"
            echo "Please add agbaccount_github_username to GitLab CI/CD Variables"
            exit 1
          fi

          # Check GitHub email variable
          if [ -z "${{vars.agbaccount_github_email}}" ]; then
            echo "❌ agbaccount_github_email not configured in GitLab Variables"
            echo "Please add agbaccount_github_email to GitLab CI/CD Variables"
            exit 1
          fi

          echo "✅ GitHub credentials and user information validated"
          echo "  - Token: Configured"
          echo "  - Username: ${{vars.agbaccount_github_username}}"
          echo "  - Email: ${{vars.agbaccount_github_email}}"

          # Determine target repository
          GITHUB_REPO="${{params.github_repo}}"

          if [ -z "$GITHUB_REPO" ]; then
            echo "❌ GitHub repository not specified"
            echo "Please set github_repo parameter"
            exit 1
          fi

          # Validate repository name format
          if [[ ! "$GITHUB_REPO" =~ ^[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+$ ]]; then
            echo "❌ Invalid GitHub repository format: $GITHUB_REPO"
            echo "Expected format: username/repository-name"
            exit 1
          fi

          # Test network connectivity
          echo "🌐 Testing network connectivity..."
          if ! ping -c 1 github.com > /dev/null 2>&1; then
            echo "⚠️ Cannot ping github.com - checking HTTP connectivity..."
            if ! curl -s --connect-timeout 10 https://github.com > /dev/null; then
              echo "❌ Cannot reach GitHub - network connectivity issue"
              echo "Please check network configuration and firewall settings"
              exit 1
            fi
          fi
          echo "✅ Network connectivity to GitHub confirmed"

          # Validate GitHub Token basic validity
          echo "🔐 Testing GitHub token validity..."
          TOKEN_TEST=$(curl -s -w "%{http_code}" -H "Authorization: token ${{secrets.agbaccount_github_token}}" \
                       "https://api.github.com/user" -o /dev/null)

          if [ "$TOKEN_TEST" != "200" ]; then
            echo "❌ GitHub token validation failed (HTTP $TOKEN_TEST)"
            case "$TOKEN_TEST" in
              "401") echo "  - Token is invalid or expired" ;;
              "403") echo "  - Token has insufficient permissions or rate limited" ;;
              "000") echo "  - Network connection failed" ;;
              *) echo "  - Unexpected error occurred" ;;
            esac
            echo "Please check your GitHub token configuration"
            exit 1
          fi
          echo "✅ GitHub token is valid"

          # Validate target repository access permissions
          echo "🔍 Testing repository access..."
          REPO_TEST=$(curl -s -w "%{http_code}" -H "Authorization: token ${{secrets.agbaccount_github_token}}" \
                      "https://api.github.com/repos/${GITHUB_REPO}" -o /dev/null)

          if [ "$REPO_TEST" != "200" ]; then
            echo "❌ Repository access validation failed (HTTP $REPO_TEST)"
            case "$REPO_TEST" in
              "404") echo "  - Repository does not exist or token lacks access" ;;
              "403") echo "  - Token has insufficient permissions for this repository" ;;
              "401") echo "  - Authentication failed" ;;
              *) echo "  - Unexpected error occurred" ;;
            esac
            echo "Please check:"
            echo "  1. Repository ${GITHUB_REPO} exists"
            echo "  2. Token has 'repo' permissions"
            echo "  3. Token owner has access to the repository"
            exit 1
          fi
          echo "✅ Repository access confirmed"

          echo "✅ GitHub configuration validated"
          echo "  - Repository: $GITHUB_REPO"
          echo "  - Token: Valid and authenticated"
          echo "  - Repository Access: Confirmed"

          echo "GITHUB_REPO=$GITHUB_REPO" >> $AONE_CI_ENV

      # Push documentation to GitHub
      - id: push-to-github
        name: "Push Documentation to GitHub"
        run: |
          echo "🚀 Starting documentation push to GitHub..."

          GITHUB_REPO="${{params.github_repo}}"

          echo "📋 Push Configuration:"
          echo "  - Repository: $GITHUB_REPO"
          echo "  - Development Branch: (will be randomly generated)"
          echo "  - Base Branch: main"
          echo "  - Files Count: $DOCS_FILES_COUNT"

          # Create working directory
          GITHUB_WORK_DIR="$PWD/.github-docs-sync"
          mkdir -p "$GITHUB_WORK_DIR"
          cd "$GITHUB_WORK_DIR"

          # Configure Git - Get user information directly from Variables
          echo "🔧 Configuring Git user information..."

          # Get username and email directly from Variables
          GITHUB_USERNAME="${{vars.agbaccount_github_username}}"
          GITHUB_EMAIL="${{vars.agbaccount_github_email}}"

          echo "📋 Git configuration:"
          echo "  - Username: $GITHUB_USERNAME"
          echo "  - Email: $GITHUB_EMAIL"

          git config --global user.name "$GITHUB_USERNAME"
          git config --global user.email "$GITHUB_EMAIL"
          git config --global init.defaultBranch main

          # Configure Git credential handling to ensure proper use of GitHub Token
          git config --global credential.helper store
          echo "https://${GITHUB_USERNAME}:${{secrets.agbaccount_github_token}}@github.com" > ~/.git-credentials

          echo "✅ Git configured with GitHub account information"

          # Validate GitHub Token and repository access permissions
          echo "🔐 Validating GitHub access..."

          # Test GitHub API access
          echo "Testing GitHub API access..."
          if ! curl -s -H "Authorization: token ${{secrets.agbaccount_github_token}}" \
               "https://api.github.com/repos/${GITHUB_REPO}" > /dev/null; then
            echo "❌ Failed to access GitHub API"
            echo "Please check:"
            echo "  1. GitHub token is valid and not expired"
            echo "  2. Token has 'repo' permissions"
            echo "  3. Repository ${GITHUB_REPO} exists and is accessible"

            # Test basic GitHub API connectivity
            echo "Testing basic GitHub connectivity..."
            if curl -s "https://api.github.com" > /dev/null; then
              echo "✅ GitHub API is reachable"
            else
              echo "❌ Cannot reach GitHub API - network issue"
            fi
            exit 1
          fi

          echo "✅ GitHub API access validated"

          # Clone GitHub repository
          echo "📥 Cloning GitHub repository..."

          # Set Git credential helper timeout
          git config --global credential.helper 'cache --timeout=300'

          # Attempt to clone GitHub repository
          if ! git clone "https://${GITHUB_USERNAME}:${{secrets.agbaccount_github_token}}@github.com/${GITHUB_REPO}.git" github-repo; then
            echo "❌ Failed to clone GitHub repository"
            echo "Debugging information:"
            echo "  - Repository: ${GITHUB_REPO}"
            echo "  - Git version: $(git --version)"

            # Try alternative clone method
            echo "Trying alternative clone method..."
            if ! git clone "https://github.com/${GITHUB_REPO}.git" github-repo; then
              echo "❌ Alternative clone method also failed"
              echo "Please check:"
              echo "  1. Repository ${GITHUB_REPO} exists and is publicly accessible"
              echo "  2. GitHub token has correct permissions"
              echo "  3. Network connectivity to GitHub"
              exit 1
            else
              echo "✅ Repository cloned without authentication"
              echo "⚠️ Will configure authentication for push operations"
              cd github-repo
              git remote set-url origin "https://${{secrets.agbaccount_github_token}}@github.com/${GITHUB_REPO}.git"
              cd ..
            fi
          else
            echo "✅ Repository cloned successfully with authentication"
          fi

          cd github-repo

          # Fetch all remote branch information
          git fetch origin

          # Determine base branch
          PR_TARGET_BRANCH="dev"

          # Set Development Branch to dev
          GITHUB_BRANCH="dev"

<<<<<<< HEAD
          echo "🔄 Creating random development branch: $GITHUB_BRANCH"
          echo "📋 Base branch: $PR_TARGET_BRANCH"
<<<<<<< ours
          
<<<<<<< ours
          # Save branch name to environment for later steps
          echo "GITHUB_BRANCH=$GITHUB_BRANCH" >> $AONE_CI_ENV
          
=======
>>>>>>> theirs
=======
=======
          echo "🔄 Target branch: $GITHUB_BRANCH"
>>>>>>> ci(docs): optimize docs sync workflow and fix config validation

          # Save branch name to environment for later steps
          echo "GITHUB_BRANCH=$GITHUB_BRANCH" >> $AONE_CI_ENV

<<<<<<< HEAD
>>>>>>> theirs
          # Check if base branch exists
          if git show-ref --verify --quiet "refs/remotes/origin/$PR_TARGET_BRANCH"; then
            echo "✅ Found base branch: $PR_TARGET_BRANCH"
            git checkout -b "$GITHUB_BRANCH" "origin/$PR_TARGET_BRANCH"
=======
          # Check if target branch exists
          if git show-ref --verify --quiet "refs/remotes/origin/$GITHUB_BRANCH"; then
            echo "✅ Found target branch: $GITHUB_BRANCH"
            git checkout -b "$GITHUB_BRANCH" "origin/$GITHUB_BRANCH"
>>>>>>> ci(docs): optimize docs sync workflow and fix config validation
          else
            echo "⚠️ Target branch $GITHUB_BRANCH not found on remote, creating new branch from default..."
            # Try to find a base to branch off from if dev doesn't exist yet
            if git show-ref --verify --quiet "refs/remotes/origin/main"; then
              git checkout -b "$GITHUB_BRANCH" "origin/main"
            elif git show-ref --verify --quiet "refs/remotes/origin/master"; then
              git checkout -b "$GITHUB_BRANCH" "origin/master"
            else
              # If explicit base not found, just use current HEAD
              git checkout -b "$GITHUB_BRANCH"
            fi
          fi

          echo "✅ Switched to branch '$GITHUB_BRANCH'"

          # Sync documentation files
          echo "📋 Syncing documentation files..."

          # Ensure target directory structure exists
          mkdir -p docs/api-reference
          mkdir -p docs/examples
          mkdir -p docs/guides

          # Copy documentation files using safe copy (cp -Rf) for specific directories only
          # This will overwrite files with same name but keep other files in destination
          echo "📂 Copying specific documentation directories..."

          # Copy specific directories
          if [ -d "../../docs" ]; then
            # Sync api-reference
            if [ -d "../../docs/api-reference" ]; then
              echo "Syncing api-reference..."
              # Safe clean: only if target directory exists
              if [ -d "./docs/api-reference" ]; then
                 rm -rf ./docs/api-reference/*
              fi
              mkdir -p ./docs/api-reference
              cp -Rfv ../../docs/api-reference/* ./docs/api-reference/
            fi

            # Sync examples
            if [ -d "../../docs/examples" ]; then
              echo "Syncing examples..."
              if [ -d "./docs/examples" ]; then
                 rm -rf ./docs/examples/*
              fi
              mkdir -p ./docs/examples
              cp -Rfv ../../docs/examples/* ./docs/examples/
            fi

            # Sync guides
            if [ -d "../../docs/guides" ]; then
              echo "Syncing guides..."
              if [ -d "./docs/guides" ]; then
                 rm -rf ./docs/guides/*
              fi
              mkdir -p ./docs/guides
              cp -Rfv ../../docs/guides/* ./docs/guides/
            fi

            echo "✅ Documentation directories synced successfully"
          else
            echo "❌ Source docs directory not found"
            exit 1
          fi

          # Display synced files
          echo "📋 Synced files:"
          find docs -type f | head -10
          TOTAL_FILES=$(find docs -type f | wc -l)
          echo "📊 Total files synced: $TOTAL_FILES"

          # Check for changes
          git add docs/

          if git diff --staged --quiet; then
            echo "📝 No changes detected in documentation"
            echo "✅ Documentation is already up to date"
          else
            # Commit changes
            COMMIT_TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
            COMMIT_MESSAGE="🤖 Auto-sync documentation from GitLab CI [$COMMIT_TIMESTAMP]

            - Synced $TOTAL_FILES documentation files
            - Source: GitLab CI Pipeline
            - Triggered by: Documentation update"

            echo "💾 Committing changes..."
            git commit -m "$COMMIT_MESSAGE"

            # Push new branch to GitHub (ensure remote branch is created)
            echo "⬆️ Pushing changes to GitHub branch $GITHUB_BRANCH..."
            if git push origin "$GITHUB_BRANCH"; then
              echo "✅ Documentation successfully pushed to GitHub!"
              echo "🔗 View at: https://github.com/${GITHUB_REPO}/tree/${GITHUB_BRANCH}/docs"

              echo "📋 Branch Details:"
              echo "  - Branch: $GITHUB_BRANCH"
              echo "  - Files Changed: $TOTAL_FILES"
              echo "  - Repository: $GITHUB_REPO"
            else
              echo "❌ Failed to push to GitHub"
              exit 1
            fi
          fi

          # Clean up working directory
          cd ../../
          rm -rf "$GITHUB_WORK_DIR"
          echo "🧹 Cleanup completed"

      # Generate push report
      - id: generate-report
        name: "Generate Push Report"
        run: |
          echo "📊 Documentation Push Report"
          echo "=================================="
          echo "✅ Pipeline Status: SUCCESS"
          echo "📅 Execution Time: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "📂 Files Processed: ${DOCS_FILES_COUNT:-0}"
          echo "🎯 Target Repository: ${GITHUB_REPO:-'Not specified'}"
          echo "🌿 Development Branch: ${GITHUB_BRANCH:-'Generated randomly'}"
          echo "🎯 Base Branch: main"


          echo "=================================="
          echo "🔗 GitHub Repository: https://github.com/${GITHUB_REPO}"
          echo "📖 Documentation: https://github.com/${GITHUB_REPO}/tree/${GITHUB_BRANCH}/docs"

          echo "📝 Development Branch: https://github.com/${GITHUB_REPO}/tree/${GITHUB_BRANCH}"

          echo "=================================="
